name: Build & Publish Dev Docker image

on:
  push:
    branches: 
      - "dev"
  workflow_dispatch:
  
jobs:
  docker:
    environment: ${{ github.ref == 'refs/heads/master' && 'prod' || github.ref == 'refs/heads/dev' && 'dev' }}
    runs-on: ubuntu-latest
    steps:
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME}}
          password: ${{ secrets.ACR_PASSWORD}} 
          
      - name: Build and push
        uses: docker/build-push-action@v5.3.0
        with:
          push: true
          tags: diouxx/glpi:dev
